### ISSUE TITLE
Callback and close functions don't work

### ISSUE THREAD

**Issue by tobieeniafe** [ashinzekene/angular-rave#1]
Hi there, the package runs correctly, but the callback and close functions do not work. Kindly see to it

**Comment by ashinzekene** [comment]
Really? would update it immediately

**Comment by tobieeniafe** [comment]
kindly notify me when you've fixed it thanks.

**Comment by ashinzekene** [comment]
It has been fixed. You can try it out now

**Comment by tobieeniafe** [comment]
Thanks a lot 🙏🏾

**Comment by tobieeniafe** [comment]
Apparently, there seems to be a version mismatch happening somewhere, causing an error in my code. All I did was uninstall and reinstall the package. I'm using angular 4.4.7

![screenshot 231](https://user-images.githubusercontent.com/18620774/40216814-ff845162-5a60-11e8-87a8-dfe5819f755b.png)

**Comment by ashinzekene** [comment]
The problem is because the module now uses angular 6

**Comment by ashinzekene** [comment]
You have to update your angular. You can follow [this guide](https://update.angular.io/)

**Comment by tobieeniafe** [comment]
Done, updating to 6 was a disaster, but it finally works. Thanks again. And kindly follow back if you don't mind 👍

**Comment by ashinzekene** [comment]
You're welcome and I mind 😁
