### ISSUE TITLE
Callback functions not called

### ISSUE THREAD

**Issue by ghost** [ashinzekene/angular-rave#10]
Hello,
I just integrated your package and it works fine but the 3 callback functions are not being called, paymentSuccess($event), paymentFailure(), paymentInit().

I am using the angular-rave component.

**Comment by ashinzekene** [comment]
You're probably not doing it the right way

**Comment by ghost** [comment]
Ok, Please do you have any sample code for angular-rave component, because I have been trying to make this work since last night, please help me

**Comment by ashinzekene** [comment]
It's on the [readme](https://github.com/ashinzekene/angular-rave/blob/master/README.md)

**Comment by ghost** [comment]
But I followed everything on the readme, don't really know what to do again.

**Comment by ghost** [comment]
I have tried the directive one, only the paymentInit() function that works for this one.

<button
  angular-rave
  [PBFPubKey] = "'FLWPUBK-XXXXXXXXXXXX'"
  [customer_email] = "'user@example.com'"
  [customer_phone] = "'08090909090'"
  [amount]="500000"
  [custom_title]="'Bill Payment'"
  [txref]="'USR1295950'"
  (callback)="paymentSuccess($event)"
  (close)="paymentFailure()"
  (init)="paymentInit()"
>PAY NOW</button>

**Comment by ashinzekene** [comment]
The rave modal should pop up, closing it would trigger the close event while successful payment should trigger the callback event

**Comment by ashinzekene** [comment]
Would look into it

**Comment by kelvinrolex** [comment]
![error](https://user-images.githubusercontent.com/10676937/51028677-70017e80-1594-11e9-844d-ddcd8a4987d1.PNG)
 that is the error I get when I use the component option
