### ISSUE TITLE
Issues with documentation

### ISSUE THREAD

**Issue by uttahb** [ashinzekene/angular-rave#11]
Hi, 
Thanks for this awesome repo, I believe there is a mistake with the current documentation where the close handler is not working as expected from documentation. I believe the close handler event in the directive should be `onclose` instead of `close`. Please advise
Thanks and regards.

**Comment by ashinzekene** [comment]
Thanks for pointing that out. You can make a PR for it if you like

**Comment by uttahb** [comment]
:) done
