### ISSUE TITLE
Adding Subaccounts

### ISSUE THREAD

**Issue by temiadesina** [ashinzekene/angular-rave#2]
Hi,
Please, We would like to use the subaccount flow on this plugin, how can we make that possible, see a link to the documentation that discusses subaccount: https://developer.flutterwave.com/v2.0/docs/split-payment

**Comment by ashinzekene** [comment]
Okay, would work on it

**Comment by temiadesina** [comment]
Hi Ashinze,

How is it going, just following up to see if you have been able to work on it?

**Comment by ashinzekene** [comment]
I have created a PR #4 for this feature. Would be merged before the end of today

**Comment by temiadesina** [comment]
Thanks Ashinze,

Hoping you can push today.

**Comment by ashinzekene** [comment]
Done. You can check now

**Comment by temiadesina** [comment]
Thanks!
