### ISSUE TITLE
PaymentInstance in Documentation

### ISSUE THREAD

**Issue by tyronasaurus-rex** [ashinzekene/angular-rave#25]
Hey!

In the documentation, i see a variable payment instance that gets created,
`paymentInstance: PaymentInstance;
`

But in paymentInit,
```
 paymentInit(paymentInstance) {
    this.paymentFailure = paymentInstance;
    console.log('Payment about to begin', paymentInstance);
  }
```

 this.paymentFailure gets set, which is a function, is this correct?

**Comment by ashinzekene** [comment]
No that was a mistake. Should be

```ts
paymentInit(paymentInstance) {
    this.paymentInstance = paymentInstance;
    console.log('Payment about to begin', paymentInstance);
  }
```


Thanks for pointing that out. You can submit a PR...
