### ISSUE TITLE
Changing text

### ISSUE THREAD

**Issue by vkyeswa** [ashinzekene/angular-rave#32]
![image](https://user-images.githubusercontent.com/5016129/77656014-4f003000-6f84-11ea-98ef-6c761799ceb9.png)
Can the package modify these texts or do you know of a way to modify them!

**Comment by ashinzekene** [comment]
Please check the readme or the [documentation](https://developer.flutterwave.com/docs/rave-inline-1#section-rave-quick-setup-embed-parameters) for a list of parameters that you can tweak

**Comment by vkyeswa** [comment]
According to the docs is `pay_button_text` but doesn't seem to effect changes

**Comment by ashinzekene** [comment]
Just checked that. I think you should reach out to them on [twitter](https://twitter.com/theflutterwave)
