### ISSUE TITLE
Confirmation Modal not closing

### ISSUE THREAD

**Issue by emmanuel-libertechy** [ashinzekene/angular-rave#33]
Hello,
I am using this module with Ionic Capacitor. After successful payment, the payment confirmation is not closed and not redirected to the app.

Here is the final url that didnt close

https://api.ravepay.co/flwv3-pug/getpaidx/api/complete?resp={%22batchno%22:%2220200422%22,%22authorizeId%22:%22558724%22,%22merchtransactionreference%22:%22FLW235718144%22,%22orderinfo%22:%22PT-FLW235718144%22,%22receiptno%22:%22011311091755%22,%22amount%22:%2250.00%22,%22responsetoken%22:%22hV7jvGG2p00CeNz\u003dVBV%22,%22responsecode%22:%2200%22,%22responsemessage%22:%22Approved%22,%22transactionreference%22:%22FLW235718144%22,%22responsehtml%22:%22%22}

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-22 at 10 19 54](https://user-images.githubusercontent.com/57720402/79965691-3f411200-8484-11ea-8847-7619d04e7fcb.png)

**Comment by ashinzekene** [comment]
This issue should be fixed if you update. Feel free to close the issue if it works

**Comment by ashinzekene** [comment]
I'm closing this. Feel free to reopen it if you still encounter this issue after updating
