### ISSUE TITLE
Callback not being called

### ISSUE THREAD

**Issue by bolorundurowb** [ashinzekene/angular-rave#34]
My specified callback function is not being called even after a successful transaction

Lib version: 2.0.1
Angular version: 9.1.3

**Comment by silvareal** [comment]
this issue is still valid

**Comment by ashinzekene** [comment]
Thanks for the feedback. It was an issue from flutterwave. There's a new update to the API. It would be implemented in this project soon

**Comment by ashinzekene** [comment]
This issue should be fixed if you update. Feel free to close the issue if it works

**Comment by ashinzekene** [comment]
I'm closing this. Feel free to reopen it if you still encounter this issue after updating
