### ISSUE TITLE
How to import the live script and also how to close payment modal on payment complete

### ISSUE THREAD

**Issue by realnsleo** [ashinzekene/angular-rave#6]
Hi!
Great plugin. I am using Angular 6 and it's working great so far. Just two questions:

1. How can I import the live script? Should I just place the reference to it in my index.html? I can see the plugin runs fine without importing anything as it used the sandbox script.

2. When payment is complete, how can I close the modal just like x.close() in the main documentation.

Thanks!

**Comment by ashinzekene** [comment]
1. I just updated the library. You don't need to import the script. The library does that for you

2. The payment modal closes automatically when a payment is completed. The `close` event is for listening for when the user closes the payment modal without completing a transaction

**Comment by realnsleo** [comment]
Thanks! I'm going to try it out again in a bit. Regarding the library, does it automatically localhost and load the sandbox script and the live for the production build? Thanks.

**Comment by ashinzekene** [comment]
No. I don't think there's any way to detect env in angular. The library uses the sandbox API though. If you provide a script in your `index.html` the library would skip fetching for the sandbox script

**Comment by realnsleo** [comment]
Thanks!

**Comment by realnsleo** [comment]
Hi,
I can confirm the payment model stays open once a payment is complete. I am using Angular 6 on a Windows 10 computer. Am I missing anything?

Thanks.

**Comment by ashinzekene** [comment]
Thanks. I just found out about that

**Comment by libertechy** [comment]
Hi 
Thanks for the plugin. Just checking if there is an update on the payment model staying opened after payment is made.

Regards,
Thanks

**Comment by ashinzekene** [comment]
Ongoing
